### ISSUE TITLE
error patching

### ISSUE THREAD

**Issue by latot** [init6/ipatch#1]
Hi, here are some things, first log:

```
ipatch ~ ../p/linux-mod.patch .
 * No such directory - ../p/linux-mod.patch
/usr/bin/ipatch: línea 396: getMimetype: no se encontró la orden
/usr/bin/ipatch: línea 396: containsElement: no se encontró la orden
/usr/bin/ipatch: línea 399: getMimetype: no se encontró la orden
```

note, the file exist:

```
dir ../*
../p:
linux-mod.patch

../t:
linux-mod.sh
```

Gentoo 64

Thx.

**Comment by init6** [comment]
1) There are no fish. [All my new work there.](https://bitbucket.org/redeyeteam/)

2) 

> ipatch ~ ../p/linux-mod.patch .

Wrong ^ Read ipatch --help

Usage: ipatch <operation> <work dir> <patch|dir|conf>

3) If error with wrong mime-type show file --mime-type linux-mod.patch

**Comment by latot** [comment]
ups, sorry for the confusion.
